### ISSUE TITLE
Not the cutest embed but nice 👍 

### ISSUE THREAD

**Issue by cipherwithadot** [HideakiAtsuyo/innocent#1]
Could be better

**Comment by HideakiAtsuyo** [comment]
> Could be better

Not made to be "cute" only to do it's job, someone suggested me to make an embed & add IP Infos I just did it :shrug:

**Comment by HideakiAtsuyo** [comment]
+ You can open a PR if you want to make something cute :)

**Comment by cipherwithadot** [comment]
Alr :)
